---
- name: Configure host.
  hosts: all

  vars_files:
    - default.config.yml

  pre_tasks:
    - name: Include playbook configuration.
      include_vars: "{{ item }}"
      with_fileglob:
        - "{{ playbook_dir }}/config.yml"
      tags: ["always"]

  roles:
    - role: elliotweiser.osx-command-line-tools
      tags: ["command-line-tools"]

    - role: geerlingguy.mac.homebrew
      tags: ["homebrew"]

    - role: geerlingguy.mac.dock
      when: configure_dock
      tags: ["dock"]

  tasks:
    - import_tasks: tasks/sudoers.yml
      when: configure_sudoers
      tags: ["sudoers"]

    - import_tasks: tasks/osx.yml
      when: configure_osx
      tags: ["osx"]

    - import_tasks: tasks/extra-packages.yml
      tags: ["extra-packages"]

    - role: geerlingguy.mac.dock
      when: configure_dock
      tags: ['dock']
