---
# TODO: Use sudo once .osx can be run via root with no user interaction.

- name: Create additional folders recursively
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: directory
    recurse: yes
  loop: "{{ folders }}"
  when: item.create | bool and item.type == 'folder'


- name: Clone git repo
  git:
    repo: "https://github.com/stiliajohny/dotfiles"
    dest: "/users/johnstilia/"
    version: "master"
    bare: yes
  tags: dotfiles
